name: Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '12 4 * * *'

jobs:
  go-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.value }}
    steps:
      - id: versions
        run: |
          versions=$(curl -s 'https://go.dev/dl/?mode=json' | jq -c 'map(.version[2:])')
          echo "value=${versions}" >> $GITHUB_OUTPUT

  plugin_test:
    needs: go-versions
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version: ${{fromJson(needs.go-versions.outputs.versions)}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: asdf_plugin_test (for Go asdf)
        uses: asdf-vm/actions/plugin-test@master
        with:
          command: go version
          gitref: ${GITHUB_REF#refs/*/}
          version: ${{ matrix.version }}
        env:
          GO_SDK_LOW_LIMIT_VERSION: 1.16.15

      - name: remove asdf
        run: |
          rm -rf ~/.asdf

      - name: asdf_plugin_test (for bash asdf)
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: go version
          gitref: ${GITHUB_REF#refs/*/}
          version: ${{ matrix.version }}
          asdf_branch: master
